platform:ios, '7.0'
target 'UnknownTheSister' do
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJRefresh', '~> 3.1.12'
pod 'DACircularProgress', '~> 2.3.1'
pod 'pop', '~> 1.0.9'
end

